version: "3.7"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      caddy_1: inclubit2.testyta.se
      caddy_1.handle_path: /hello*
      caddy_1.handle_path.reverse_proxy: "host.docker.internal:8000"
      # caddy.reverse_proxy: "host.docker.internal:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker-data/caddy:/data
    restart: unless-stopped

networks:
  caddy:
    external: true

# volumes:
#   caddy_data: {}