version: "3.7"

services:
  # project-folder:
  #   build: ../
  # mediaserver:
  #   build: ./mediaserver
  #   network_mode: "host"
  auth:
    build: ./auth
    env_file:
      - .env
    # ports:
    #   - "3333:3333"
    # networks:
    #   - caddy
    labels:
      caddy: inclubit2.testyta.se
      caddy.handle_path: /auth*
      caddy.handle_path.reverse_proxy: "{{upstreams 3333}}"
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=bajskorv
      - POSTGRES_DB=inclubit
    ports:
      - "5432:5432"
networks:
  default:
    external: true
    name: caddy
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - "8989:8080"
