# THIS FILE DOES OVERRIDES FOR DEVELOPING THE APP WITH HOT RELOAD AND SUCH
version: "3.5"

services:
  mediaserver:
    command: yarn run dev
    volumes:
      - ./mediaserver/src:/usr/app/src
      # - /usr/src/app/node_modules