# THIS FILE DOES OVERRIDES FOR DEVELOPING THE APP WITH HOT RELOAD AND SUCH
version: "3.5"

services:
  mediaserver:
    command: yarn run dev
    volumes:
      - ./mediaserver/src:/usr/app/src
      # - /usr/src/app/node_modules
    network_mode: "bridge"
    ports:
      - "9001:9001"
      - "22000-22040:22000-22040"